# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - braedens-backend-development

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://braedensimages.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_0af6fd9cf64e4e51bbd1d3d5dc08adcd }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c73741d7956d4194ad1e21f35d70d98b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: braedensimages.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0af6fd9cf64e4e51bbd1d3d5dc08adcd }}/braedens-backend-development:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'braedens-backend-development'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_49219796eb0f49c8ace54a67c44fc7b9 }}
        images: 'braedensimages.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0af6fd9cf64e4e51bbd1d3d5dc08adcd }}/braedens-backend-development:${{ github.sha }}'